name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        image: html
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      run: |
        IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/image:latest${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE
