name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env: 
        image_name: html


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Container Registry
      run: echo "${{ secrets.GCP_SA_KEY }}" 
      #| docker login -u _json_key --password-stdin https://gcr.io

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/image_nameE:latest${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/image_name:latest${{ github.sha }}
