name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env: 
        image_name: html
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    #- name: install the gcloud cli
      #uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/$GCP_PROJECT/web/image_name:latest .
        docker push us-central1-docker.pkg.dev/$GCP_PROJECT/web/image_name:latest