name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        images: html
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}
       

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker images
      run: |
        IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/images:latest${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE
